on: [push]
name: Format Check
jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.push.head.sha }}
      - name: Format Check
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
