on: [push]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.15.x, 1.16.x, 1.17.x ]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.push.head.sha }}
      - name: Install Dependences
        run: go mod download
      - name: Go Test
        run: go test ./...
  test-race:
    strategy:
      matrix:
        go-version: [ 1.15.x, 1.16.x, 1.17.x ]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.push.head.sha }}
      - name: Install Dependences
        run: go mod download
      - name: Go Test Race
        run: go test ./... -race
